### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Vishal-raj-1**
I have add list of topic and video resources for those topics. It looks nice.

But these video resources are from same playlist. So I want to suggest one more way to make README.md more efficiently. We can removes links of videos from each topic and provide the link of playlist in Resources section of README.md

And We can make table with two column where first column consists topic and second column is consist of short description. I think this will rock README.md.

Suggest me what to do @urvashi-code1255 😉

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
Yes, I think it's nice

**Comment by urvashi-code1255** [comment]
Making table is a good idea go for it😄

**Review by urvashi-code1255 — CHANGES_REQUESTED** [review]
Please do it using table

**Comment by Vishal-raj-1** [comment]
I will do that in new PR. Merge it for now.

**Review by urvashi-code1255 — APPROVED** [review]

**Pull request merged**
